<a href="https://colab.research.google.com/github/taufiq-2004/Data-science-portfolio/blob/main/Day09_NumPy_Advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr=np.array([[1,2,3], [4,5,6]])

print("Original Array\n", arr)

print("\narr + 10", arr + 10)


b=np.array([1,0,1])
print("\narr+b", arr + b)

Original Array
 [[1 2 3]
 [4 5 6]]

arr + 10 [[11 12 13]
 [14 15 16]]

arr+b [[2 2 4]
 [5 5 7]]


In [2]:
matrix= np.array([[1,2,3], [4,5,6]])

print({"Sum of Matrix", np.sum(matrix)})
print("Sum of matrix axis = 0", np.sum(matrix, axis=0))
print("Sum of Matrix axis = 1", np.sum(matrix, axis=1))

{'Sum of Matrix', np.int64(21)}
Sum of matrix axis = 0 [5 7 9]
Sum of Matrix axis = 1 [ 6 15]


In [3]:
a=np.array([[1,2], [3,4]])
b=np.array([[5,6], [7,8]])

print("Element wise:", a*b)
print("Matrix Multiplication", a @ b)

Element wise: [[ 5 12]
 [21 32]]
Matrix Multiplication [[19 22]
 [43 50]]


In [5]:
x=np.array([1,2,3])
y=np.array([4,5,6])

v_stack=np.vstack((x,y))
h_stack=np.hstack((x,y))

print("Vertical Stack", v_stack)
print("Horizontal Stack", h_stack)

arr=np.arange(10,3)
split=np.split(arr, 3)

print("After Split", split)

Vertical Stack [[1 2 3]
 [4 5 6]]
Horizontal Stack [1 2 3 4 5 6]
After Split [array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [6]:
np.random.seed(42)
rand_nums=np.random.randint(0, 100, (3, 3))
print("Random Matrix With seed 42\n", rand_nums)

Random Matrix With seed 42
 [[51 92 14]
 [71 60 20]
 [82 86 74]]


In [7]:
a=np.random.randint(0, 100, (3, 3))
b=np.array([1,2,3])
print("A + B", a+b)

A + B [[ 75  89 102]
 [ 24   4  24]
 [ 53   3  90]]


In [8]:
row_mean=np.mean(a, axis=1)
column_mean=np.mean(a, axis=0)

print("Row-Wise Mean", row_mean)
print("Column-Wise Mean", column_mean)

Row-Wise Mean [86.66666667 15.33333333 46.66666667]
Column-Wise Mean [49.66666667 30.         69.        ]


In [9]:
x=np.array([[1,2], [3,4]])
y=np.array([[5,6], [7,8]])

print("X", x)
print("Y", y)
print("x * y", x*y)
print("X @ Y", x@y)


X [[1 2]
 [3 4]]
Y [[5 6]
 [7 8]]
x * y [[ 5 12]
 [21 32]]
X @ Y [[19 22]
 [43 50]]


In [10]:
arr1=np.array([10,20,30])
arr2=np.array([40,50,60])

v_stacked=np.vstack((arr1, arr2))
print("Vertically Stacked", v_stacked)


Vertically Stacked [[10 20 30]
 [40 50 60]]


In [11]:
arr=np.arange(1,13)
a_split=np.split(arr, 4)
print("Original Array", arr)
print("Split", a_split)

Original Array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Split [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]


In [12]:
np.random.seed(42)
matrix1=np.random.randint(0, 100, (3, 3))
np.random.seed(42)
matrix2=np.random.randint(0, 100, (3, 3))
print("Matrix 1\n", matrix1)
print("\nMatrix 2\n", matrix2)

Matrix 1
 [[51 92 14]
 [71 60 20]
 [82 86 74]]

Matrix 2
 [[51 92 14]
 [71 60 20]
 [82 86 74]]
