<a href="https://colab.research.google.com/github/taufiq-2004/Data-science-portfolio/blob/main/Day08_NumPy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
matrix=np.array([[1,2,3], [4,5,6]])
print("Matrix", matrix)
print("Matrix Shape", matrix.shape)
print("Dimension", matrix.ndim)

Matrix [[1 2 3]
 [4 5 6]]
Matrix Shape (2, 3)
Dimension 2


In [ ]:
zeros=np.zeros((2,3))
ones=np.ones((3,2))
arange=np.arange(0,10,2)
linspace=np.linspace(0,1,5)

print(zeros)
print(ones)
print(arange)
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[1:4])
arr[2]=100
print(arr)

10
[20 30 40]
[ 10  20 100  40  50]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a**b)
print(np.sqrt(a))
print(np.mean(b))

[5 7 9]
[ 4 10 18]
[  1  32 729]
[1.         1.41421356 1.73205081]
5.0


In [3]:
data=np.arange(1,10).reshape(3,3)
print(data)
print("Transpose\n", data.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
random_arr=np.random.rand(3,3)
random_int=np.random.randint(1,100,5)

print(random_arr)
print(random_int)


[[0.81752194 0.38945625 0.48866628]
 [0.08676895 0.85460641 0.79748018]
 [0.16116362 0.06514078 0.98995677]]
[78  9 11 45 48]


In [5]:
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


In [18]:
import numpy as np

arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


In [19]:
reshaped_arr=arr[:-1].reshape(2,4)
print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[10 15 20 25]
 [30 35 40 45]]


In [13]:
mean_val=np.mean(reshaped_arr)
median_val=np.median(reshaped_arr)
std_val=np.std(reshaped_arr)

print("Mean", mean_val)
print("Median", median_val)
print("Standard_deviation", std_val)

Mean 27.5
Median 27.5
Standard_deviation 11.4564392373896


In [15]:
filtered_val=reshaped_arr[reshaped_arr>30]
print(filtered_val)

[35 40 45]


In [22]:
rand_arr=np.random.randint(1, 21,(3,3))
print(rand_arr)

[[ 6  7  8]
 [ 8 15 13]
 [14 11 20]]


In [35]:
r=np.random.randint(1,51,(3,3))

print(r)
print(r.T)
print(r.ndim)
print(r.shape)

[[37  8 17]
 [24 29 44]
 [50  1 32]]
[[37 24 50]
 [ 8 29  1]
 [17 44 32]]
2
(3, 3)
